<?php

namespace AppBundle\Repository;

/**
 * ListRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserListsRepository extends \Doctrine\ORM\EntityRepository
{
}
